type State {
    _id: ID!
    nome: String!
    siglaEstado: String!
    pais: Country!
}

type Query {
    estados: [State!]!
    getEstadoById(id: ID!): State!
    getEstadoByNome(nome: String!): State!
    getEstadoBySigla(siglaEstado: String!): State!
}

input StateInput {
    nome: String!
    siglaEstado: String!
    pais: ID!
}

type Mutation {
    createState(data: StateInput!): State!
    updateState(id: ID!, data: StateInput!): State!
    deleteState(id: ID!): Boolean
}