type Country {
    _id: ID!
    nome: String!
    siglaPais: String!
    capital: String!
    # estados: [State]!
}

type Query {
    paises: [Country!]!
    getPaisById(id: ID!): Country!
    getPaisByNome(nome: String!): Country!
    getPaisByCapital(capital: String!): Country!
    getPaisBySigla(siglaPais: String!): Country!
}

input CountryInput {
    nome: String!
    siglaPais: String!
    capital: String!
    # estados: [State]!
}

type Mutation {
    createCountry(data: CountryInput!): Country!
    updateCountry(id: ID!, data: CountryInput!): Country!
    deleteCountry(id: ID!): Boolean
}